In [1]:
import sqlite3
import pandas as pd

df = pd.read_csv('../data/cleaned_dataset.csv')
conn = sqlite3.connect('../data/analytics_db.db')
df.to_sql('sales_data', conn, if_exists='replace', index=False)
print("Data successfully imported into SQLite database!")

Data successfully imported into SQLite database!

In [2]:
query1 = "SELECT COUNT(*) AS total_rows FROM sales_data;"
pd.read_sql(query1, conn)

   total_rows
0        6764

In [3]:

query2 = """
SELECT Category, SUM(Sales) AS total_sales
FROM sales_data
GROUP BY Category
ORDER BY total_sales DESC
LIMIT 5;
"""
pd.read_sql(query2, conn)

          Category  total_sales
0  Office Supplies  197919.7310
1        Furniture  139295.2317
2       Technology  122763.4280

In [4]:
query3 = """
WITH AvgSales AS (
    SELECT AVG(Sales) AS avg_sale FROM sales_data
    )
    SELECT * FROM sales_data, AvgSales
    WHERE Sales > avg_sale
    LIMIT 10;
    """
pd.read_sql(query3, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,avg_sale
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136,68.003902
1,10,CA-2014-115812,9/6/2014,14/6/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.900,5,0.0,34.4700,68.003902
2,20,CA-2014-143336,27/8/2014,1/9/2014,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.480,3,0.2,16.0110,68.003902
3,24,US-2017-156909,16/7/2017,18/7/2017,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,0.3,-1.0196,68.003902
4,27,CA-2016-121755,16/1/2016,20/1/2016,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,...,West,TEC-AC-10003027,Technology,Accessories,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive,90.570,3,0.0,11.7741,68.003902
5,30,US-2015-150630,17/9/2015,21/9/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,East,FUR-FU-10004848,Furniture,Furnishings,"Howard Miller 13-3/4"" Diameter Brushed Chrome ...",124.200,3,0.2,15.5250,68.003902
6,32,US-2015-150630,17/9/2015,21/9/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,East,OFF-AR-10004042,Office Supplies,Art,"BOSTON Model 1800 Electric Pencil Sharpeners, ...",86.304,6,0.2,9.7092,68.003902
7,38,CA-2015-117415,27/12/2015,31/12/2015,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,...,Central,OFF-EN-10002986,Office Supplies,Envelopes,"#10-4 1/8"" x 9 1/2"" Premium Diagonal Seam Enve...",113.328,9,0.2,35.4150,68.003902
8,40,CA-2015-117415,27/12/2015,31/12/2015,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,...,Central,FUR-CH-10004218,Furniture,Chairs,"Global Fabric Manager's Chair, Dark Gray",212.058,3,0.3,-15.1470,68.003902
9,41,CA-2015-117415,27/12/2015,31/12/2015,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,...,Central,TEC-PH-10000486,Technology,Phones,Plantronics HL10 Handset Lifter,371.168,4,0.2,41.7564,68.003902